version: "{build}"
skip_tags: true
clone_folder: c:\gopath\src\github.com\lifei6671\go-git-webhook
clone_depth: 1

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.8
  matrix:
    - tbs_arch: "x86"
      tbs_tools: "mingw"
      tbs_static_runtime: 1
      GOARCH: 386

    - tbs_arch: "x64"
      tbs_tools: "mingw"
      tbs_static_runtime: 1
      GOARCH: amd64

install:
  - ps:  Start-FileDownload  https://github.com/Masterminds/glide/releases/download/v0.12.3/glide-v0.12.3-windows-amd64.zip;
         7z x -oC:\ glide-v0.12.3-windows-amd64.zip | out-null;
         copy C:\windows-amd64\glide.exe c:\go\bin\ ;
  - set PATH=%GOBIN%;%PATH%
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - glide update

build: false
deploy: true

test_script:
  - go build -v -tags "pam" -ldflags "-w"

notifications:
  - provider: Email
    to:
      - lifei6671@163.com
    on_build_success: false